[build]
  command = "echo 'No static build command needed, just functions'" 
  publish = "." 

[functions]
  node_bundler = "nft"

  included_files = [
    "views/**",
    "public/**"
  ]
  
  external_node_modules = ["express", "pug", "debug", "http-errors", "cookie-parser", "morgan", "cors"]


[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
